services:
  db:
    image: mysql:8.0
    container_name: ipes6_db
    restart: always
    environment:
      MYSQL_DATABASE: ipes6
      MYSQL_USER: ipes_user
      MYSQL_PASSWORD: REDACTED
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: ipes6_backend
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_ENV: production
      SECRET_KEY: "change-me-in-prod-please"
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
      DB_ENGINE: mysql
      DB_NAME: ipes6
      DB_USER: ipes_user
      DB_PASSWORD: REDACTED
      DB_HOST: db
      DB_PORT: 3306
      CORS_ALLOWED_ORIGINS: "http://localhost:80,http://127.0.0.1:80"
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

  frontend:
    build: ../frontend
    container_name: ipes6_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
